
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class centrosAislamiento
{

    public int id { get; set; }

    public Nullable<int> id_diario { get; set; }

    public Nullable<int> id_provincia { get; set; }

    public string centro { get; set; }

    public string personal { get; set; }

    public Nullable<int> habilitadas { get; set; }

    public Nullable<int> ocupadas { get; set; }

    public Nullable<int> disponibles { get; set; }

}

}
