
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class centro
{

    public int id_centro { get; set; }

    public Nullable<int> id_diario { get; set; }

    public Nullable<int> total_centros { get; set; }

    public Nullable<int> id_cama { get; set; }

    public Nullable<int> id_uci { get; set; }

    public Nullable<int> id_ventilador { get; set; }

    public string tipo_centro { get; set; }

}

}
