//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class interdicciones_migratorias
    {
        public int id { get; set; }
        public Nullable<int> id_diario { get; set; }
        public Nullable<int> id_provincia { get; set; }
        public Nullable<int> erd { get; set; }
        public Nullable<int> ftci { get; set; }
        public Nullable<int> cesfront { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
