
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class Municipio
{

    public int Id { get; set; }

    public Nullable<int> IdRegion { get; set; }

    public Nullable<int> IdProvincia { get; set; }

    public Nullable<int> IdMunicipio { get; set; }

    public string Nombre { get; set; }



    public virtual Provincia Provincia { get; set; }

}

}
