//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public int Id { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public string Nombre { get; set; }
    
        public virtual Provincia Provincia { get; set; }
    }
}
