//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int id_nota { get; set; }
        public Nullable<int> id_institucion { get; set; }
        public Nullable<int> id_diario { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_provincia { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public Nullable<int> id_sector { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string direccion { get; set; }
        public string detalles { get; set; }
        public Nullable<int> eliminado { get; set; }
    }
}
