
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class nota
{

    public int id_nota { get; set; }

    public Nullable<int> id_institucion { get; set; }

    public Nullable<int> id_diario { get; set; }

    public Nullable<int> id_usuario { get; set; }

    public Nullable<int> id_provincia { get; set; }

    public Nullable<int> id_municipio { get; set; }

    public Nullable<int> id_sector { get; set; }

    public string asunto { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public Nullable<System.TimeSpan> hora { get; set; }

    public string direccion { get; set; }

    public string detalles { get; set; }

    public Nullable<int> eliminado { get; set; }

}

}
