//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class nuevos_casos_hoy
    {
        public int id { get; set; }
        public Nullable<int> id_diario { get; set; }
        public Nullable<int> confirmados { get; set; }
        public Nullable<int> fallecidos { get; set; }
        public Nullable<int> nuevasPruebas { get; set; }
    }
}
