
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class nuevos_casos_hoy
{

    public int id { get; set; }

    public Nullable<int> id_diario { get; set; }

    public Nullable<int> confirmados { get; set; }

    public Nullable<int> fallecidos { get; set; }

    public Nullable<int> nuevasPruebas { get; set; }

}

}
