
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class operaciones_realizadas
{

    public int id { get; set; }

    public Nullable<int> id_diario { get; set; }

    public Nullable<int> lugar { get; set; }

    public string unidad { get; set; }

    public Nullable<int> personas_detenidas { get; set; }

    public Nullable<int> vehiculos_detenidos { get; set; }

    public string mercancia_retenida { get; set; }

}

}
