//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class operaciones_realizadas
    {
        public int id { get; set; }
        public Nullable<int> id_diario { get; set; }
        public Nullable<int> lugar { get; set; }
        public string unidad { get; set; }
        public Nullable<int> personas_detenidas { get; set; }
        public Nullable<int> vehiculos_detenidos { get; set; }
        public string mercancia_retenida { get; set; }
    }
}
