
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class relacion_personal_vehiculos_puntosFijos
{

    public int id { get; set; }

    public Nullable<int> id_diario { get; set; }

    public Nullable<int> id_institucion { get; set; }

    public Nullable<int> ccm { get; set; }

    public Nullable<int> ccn { get; set; }

    public Nullable<int> ccs { get; set; }

    public Nullable<int> cce { get; set; }

    public Nullable<int> vehiculos { get; set; }

    public Nullable<int> motocicletas { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

}

}
