//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class relacion_personal_vehiculos_puntosFijos
    {
        public int id { get; set; }
        public Nullable<int> id_diario { get; set; }
        public Nullable<int> id_institucion { get; set; }
        public Nullable<int> ccm { get; set; }
        public Nullable<int> ccn { get; set; }
        public Nullable<int> ccs { get; set; }
        public Nullable<int> cce { get; set; }
        public Nullable<int> vehiculos { get; set; }
        public Nullable<int> motocicletas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
