//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public int id { get; set; }
        public int IdRegion { get; set; }
        public int IdProvincia { get; set; }
        public int IdMunicipio { get; set; }
        public int IdDistritoMunicipal { get; set; }
        public int IdSector { get; set; }
        public string Nombre { get; set; }
    }
}
