
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class seguimientocasospositivoscovid
{

    public int id { get; set; }

    public Nullable<int> id_usuario { get; set; }

    public Nullable<int> id_diario { get; set; }

    public Nullable<int> id_provincia { get; set; }

    public Nullable<int> visitas_realizadas { get; set; }

    public Nullable<int> equipos { get; set; }

    public Nullable<int> visitas_acomuladas { get; set; }

    public Nullable<int> fallecidos { get; set; }

    public Nullable<int> traslados { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

}

}
