
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SINFA.Models.C5i.DB_SQL_EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class usuario
{

    public int id_usuario { get; set; }

    public Nullable<int> id_institucion { get; set; }

    public Nullable<int> id_rango { get; set; }

    public string nombres { get; set; }

    public string apellidos { get; set; }

    public string cedula { get; set; }

    public string telefono { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<int> acceso { get; set; }

    public string usuario1 { get; set; }

    public string clave { get; set; }

}

}
